# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# TCL: imports/lab3/pins.tcl

# XDC: new/lab4_const.xdc

# Block Designs: bd/lab3_bd/lab3_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd || ORIG_REF_NAME==lab3_bd} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_processing_system7_0_0/lab3_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_processing_system7_0_0 || ORIG_REF_NAME==lab3_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_xbar_0/lab3_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_xbar_0 || ORIG_REF_NAME==lab3_bd_xbar_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_ps7_0_axi_periph_0/lab3_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab3_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_rst_ps7_0_50M_0/lab3_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==lab3_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_AUP_advanced_SoC_0_5/lab3_bd_AUP_advanced_SoC_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_AUP_advanced_SoC_0_5 || ORIG_REF_NAME==lab3_bd_AUP_advanced_SoC_0_5} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_axi_vdma_0_0/lab3_bd_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_axi_vdma_0_0 || ORIG_REF_NAME==lab3_bd_axi_vdma_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_axis_subset_converter_0_0/lab3_bd_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_axis_subset_converter_0_0 || ORIG_REF_NAME==lab3_bd_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_v_axi4s_vid_out_0_0/lab3_bd_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==lab3_bd_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_rgb2dvi_0_0/lab3_bd_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_rgb2dvi_0_0 || ORIG_REF_NAME==lab3_bd_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_v_tc_0_0/lab3_bd_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_v_tc_0_0 || ORIG_REF_NAME==lab3_bd_v_tc_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_axi_dynclk_0_0/lab3_bd_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_axi_dynclk_0_0 || ORIG_REF_NAME==lab3_bd_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_xlconstant_0_0/lab3_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_xlconstant_0_0 || ORIG_REF_NAME==lab3_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_axi_mem_intercon_0/lab3_bd_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_axi_mem_intercon_0 || ORIG_REF_NAME==lab3_bd_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_auto_pc_0/lab3_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_auto_pc_0 || ORIG_REF_NAME==lab3_bd_auto_pc_0} -quiet] -quiet

# IP: bd/lab3_bd/ip/lab3_bd_auto_pc_1/lab3_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_bd_auto_pc_1 || ORIG_REF_NAME==lab3_bd_auto_pc_1} -quiet] -quiet

# XDC: z:/EE_277/lab4/lab3_viv/lab3_viv.gen/sources_1/bd/lab3_bd/lab3_bd_ooc.xdc
