# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/EE_277/lab4/lab3_viv/lab3_viv.srcs/sources_1/bd/lab3_bd/ip/lab3_bd_processing_system7_0_0/lab3_bd_processing_system7_0_0.xci
# IP: The module: 'lab3_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/EE_277/lab4/lab3_viv/lab3_viv.gen/sources_1/bd/lab3_bd/ip/lab3_bd_processing_system7_0_0/lab3_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: Z:/EE_277/lab4/lab3_viv/lab3_viv.srcs/sources_1/bd/lab3_bd/ip/lab3_bd_processing_system7_0_0/lab3_bd_processing_system7_0_0.xci
# IP: The module: 'lab3_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/EE_277/lab4/lab3_viv/lab3_viv.gen/sources_1/bd/lab3_bd/ip/lab3_bd_processing_system7_0_0/lab3_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
